# Generated by Django 5.0.2 on 2024-03-05 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMetaData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoPath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_path', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.videometadata')),
            ],
        ),
    ]
